<?php

namespace AhoraMadrid\DonacionesBundle\Entity;

/**
 * CampaniaMicrocreditosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaniaMicrocreditosRepository extends \Doctrine\ORM\EntityRepository
{
}
