<?php

namespace AhoraMadrid\DonacionesBundle\Entity;

/**
 * CampaniaDonacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampaniaDonacionesRepository extends \Doctrine\ORM\EntityRepository
{
}
