<?php

namespace AhoraMadrid\DonacionesBundle\Entity;

/**
 * DonacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonacionRepository extends \Doctrine\ORM\EntityRepository{
}
