<?php

namespace AhoraMadrid\InscripcionInterventoresBundle\Entity;

/**
 * InscritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscritoRepository extends \Doctrine\ORM\EntityRepository
{
}
